#!/usr/bin/env perl

use warnings;
use strict;
use Digest::MD5 qw| md5 md5_hex md5_base64 |;
use WWW::Curl::Easy;
use Cwd;
die "Environment variables not set. Bailing.\n" if ( not defined $ENV{DESMAN_ENV} and not defined $ENV{OPENSHIFT_DEPLOYMENT_BRANCH} );
my ( $uploads, $depdir, $tmpdir, $install, $ver_file, $wp_config, $wp_plugins, $wp_themes );
# default to using cwd as repodir
my $repodir = cwd();
my $basedir = $repodir;
my $datadir = "/var/desman/data";
my $docroot = "/var/www";
my $confdir = "$repodir/config";
  
if ( defined $ENV{DESMAN_ENV} ) {
  # This should be Gen2
  $basedir =~ s/.*(\/websites.*)/$1/;
  if ( not defined $ENV{DESMAN_CONTAINERIZER} ) {
    $repodir = "$basedir/repo";
    $datadir = "$basedir/data";
    $docroot = "$basedir/htdocs";
  }
  $depdir = "$basedir/deps";
  $tmpdir = '/var/tmp';
  $uploads = "$docroot/wp-content/uploads";
  $install = $docroot;
  die "$uploads is not a link, continuing would overwrite. Halting instead.\n" if -d $uploads and not -l $uploads;
} else {
  $repodir = $ENV{OPENSHIFT_REPO_DIR};
  $depdir = $ENV{OPENSHIFT_BUILD_DEPENDENCIES_DIR};
  $tmpdir = $ENV{OPENSHIFT_TMP_DIR};
  $datadir = $ENV{OPENSHIFT_DATA_DIR};

  $repodir =~ s/\/$//;
  $depdir =~ s/\/$//;
  $tmpdir =~ s/\/$//;
  $datadir =~ s/\/$//;

  ( $docroot, $install ) = ( "$repodir/php", "$datadir/current" );
}

$ver_file = "$repodir/VERSION";
$wp_config = "$confdir/wp-config.php";
$wp_plugins = "$repodir/plugins";
$wp_themes = "$repodir/themes";
my $stamp = time;
my $curl = WWW::Curl::Easy->new;
my $md5 = Digest::MD5->new;

my $wpversion;
if ( -e $ver_file ) {
    open(WP_VERSION,"<$ver_file");
    $wpversion = <WP_VERSION>;
    chomp($wpversion);
    close(WP_VERSION);
} else {
    $wpversion = "3.9.1";
}

if ( not -f "$repodir/.inetu/salt.php" ) {
  print "Writing new SALT... ";
  my $saltf;
  open($saltf,">","$repodir/.inetu/salt.php") or die "Failed to open salt: $!";
  print $saltf "<?php\n";
  my $salturl = "https://api.wordpress.org/secret-key/1.1/salt/";
  $curl->setopt( CURLOPT_URL, $salturl );
  $curl->setopt( CURLOPT_WRITEDATA, \$saltf );
  my $saltstat = $curl->perform;
  if ( $saltstat == 0 ) {
    print "Done\n";
  } else {
    warn "Failed to write new SALT";
  }
}

my $build = "$depdir/$wpversion";

sub getmd5 {
    my ( $data, $pointer ) = @_;
    ${$pointer} .= $data;
    return length($data);
}

if ( not -f "$depdir/wordpress-$wpversion.tar.gz" ) {
    print "Downloading WordPress Version $wpversion... \n";
    mkdir $depdir if not -d $depdir ;
    open(TARBALL,">","$depdir/wordpress-$wpversion.tar.gz");
    my $url = "https://wordpress.org/wordpress-$wpversion.tar.gz";
    my $md5url = "$url.md5";
    my $expected_md5;
    $curl->setopt( CURLOPT_URL, $url );
    $curl->setopt( CURLOPT_WRITEDATA, \*TARBALL );
    my $retcode = $curl->perform;
    if ( $retcode == 0 ) {
        print "Verifying archive integrity now... \n";
        $curl = WWW::Curl::Easy->new;
        $curl->setopt( CURLOPT_URL, $md5url );
        $curl->setopt( CURLOPT_WRITEFUNCTION, \&getmd5 );
        $curl->setopt( CURLOPT_FILE, \$expected_md5 );
        my $gotmd5 = $curl->perform;
        if ( $gotmd5 == 0 ) {
            close(TARBALL);
            open(TARBALL,"<","$depdir/wordpress-$wpversion.tar.gz");
            $md5->addfile(\*TARBALL);
            my $actual_md5 = $md5->hexdigest;
            if ( $actual_md5 ne $expected_md5 ) {
                warn "Downloaded archive does not match expected md5 checksum!";
                print STDERR "expected $expected_md5 ... got $actual_md5";
                exit 2;
            }
            close(TARBALL);
        } else {
            warn "Failed to get md5 from wordpress.org!";
            exit 2;
        }
    } else {
        warn "failed to get archive from wordpress.org";
        exit 2;
    }
    close(TARBALL);
}

mkdir $build if not -d $build ;
`/bin/tar --strip-components=1 -xzf $depdir/wordpress-$wpversion.tar.gz -C $build`;
`/bin/rm -rf $docroot` if -d $docroot;
unlink $docroot if -l $docroot;
eval {
    print "Copying Wordpress configuration in $wp_config...\n";
    `cp -f $wp_config $build/wp-config.php`;
} if -f $wp_config;

if ( -d "$confdir/w3tc-config" ) {
  print "Setting up W3 Total Cache... ";
  `cp -rf $confdir/w3tc-config $build/wp-content/w3tc-config`;
  `cp -f $confdir/w3tc-nginx.conf $build/nginx.conf` if -f "$confdir/w3tc-nginx.conf";
  `cp -f $wp_plugins/w3-total-cache/wp-content/advanced-cache.php $build/wp-content/advanced-cache.php`;
  `cp -f $wp_plugins/w3-total-cache/wp-content/object-cache.php $build/wp-content/object-cache.php`;
  mkdir "$build/wp-content/cache" if not -d "$build/wp-content/cache";
  print "Done\n";
}

if ( -d $install and not defined $ENV{DESMAN_CONTAINERIZER} ) {
    print "Removing installdir [$install] now... ";
    `/bin/rm -rf $install`;
    `rm -rf $datadir/{plugins,themes}`;
    print "Done\n";
} 

print "Copying WordPress plugins from repository... ";
`/usr/bin/rsync -az $wp_plugins/ $build/wp-content/plugins/ 2>/dev/null`;
print "Done\nCopying WordPress themes from repository... ";
`/usr/bin/rsync -az $wp_themes/ $build/wp-content/themes/ 2>/dev/null`;
print "Done\n";

if ( not -d $install ) {
  print "Creating install directory [$install] now... ";
  mkdir $install;
  print "Done\n";
}
print "Copying build files to installdir now... ";
qx|/usr/bin/rsync -av --delete --force $build/ $install/ 2>/dev/null|;
print "Done\n";

print "Checking for additional apache configuration directives... ";
link "$confdir/.htaccess" , "$install/.htaccess" if -f "$confdir/.htaccess";
print "Done\n";

mkdir $datadir if not -d $datadir ;
mkdir "$datadir/uploads" if not -d "$datadir/uploads";
mkdir "$datadir/blogs.dir" if not -d "$datadir/blogs.dir";

symlink $install, $docroot if not defined $ENV{DESMAN_CONTAINERIZER};
symlink "$datadir/blogs.dir", "$docroot/wp-content/blogs.dir";
symlink "$datadir/plugins", "$docroot/wp-content/plugins";
symlink "$datadir/themes", "$docroot/wp-content/themes";
symlink "$datadir/uploads", $uploads;
qx|rm -rf $build 2>/dev/null|;
if ( not defined $ENV{DESMAN_CONTAINERIZER} or $ENV{DESMAN_CONTAINERIZER} ne "docker" ) {
  # Fix up permissions in IaaS
  if ( defined $ENV{DESMAN_ENV} ) {
    # set group to nfsnobody in stage and prod
    my $group = 'nfsnobody';
    my $dperm = '2755';
    my $fperm = '0644';
    if ( $ENV{DESMAN_ENV} eq 'devel' ) {
      $group = qx|basename `dirname $basedir`|;
      $dperm = '2775';
      $fperm = '0664';
    } 
    chomp($group);
    qx|chown -R nfsnobody:nfsnobody $docroot|;
    qx|chown -R apache:$group $datadir|;
    qx|find $datadir/uploads -type f -exec chmod $fperm {} \\;|;
    qx|find $datadir/uploads -type d -exec chmod $dperm {} \\;|;
    qx|chown apache:nfsnobody $docroot/wp-content/cache $docroot/wp-content/w3tc-config| if -d "$docroot/wp-content/w3tc-config";
    qx|chmod 755 $docroot/wp-content/cache $docroot/wp-content/w3tc-config| if -d "$docroot/wp-content/w3tc-config";
  }
} else {
  # do docker things
  print "INSTALL: $install\nDOCROOT: $docroot\nDATADIR: $datadir\n";
}
